import ApiMethodFactory from "../../utils/ApiMethodFactory"

export const config = {
  EndPoint: "api/hirServlet",
  Service: "SectionService",
  Module: "hir",
  Actions: {
    addOfferingFinancials: "addOfferingFinancials",
    addInstructorFinancials: "addInstructorFinancials",
    addMarketingProgramFinancials: "addMarketingProgramFinancials",
    addResourceFinancials: "addResourceFinancials",
    addSectionDiscount: "addSectionDiscount",
    getSectionDetails: "getSectionDetails",
    getSectionStatistics: "getSectionStatistics",
    findAffiliatedOrgsForSeatGroup: "findAffiliatedOrgsForSeatGroup",
    getPaymentGatewayAccount: "getPaymentGatewayAccount",
    getSeatGroupsBySection: "getSeatGroupsBySection",
    getCoordinator: "getCoordinator",
    updateSection: "updateSection",
    saveAffiliatedOrg: "saveAffiliatedOrg",
    updateSectionNotification: "updateSectionNotification",
    SectionNoticeID: "SectionNoticeID",
    findSectionNoticeRecipients: "findSectionNoticeRecipients",
    updateSectionFinancialMaps: "updateSectionFinancialMaps",
    copySection: "copySection",
    getMeetings: "getMeetings",
    createMeetings: "createMeetings",
    saveMeetings: "saveMeetings",
    saveFinancial: "saveFinancial",
    saveFinancials: "saveFinancials",
    getSectionFinancials: "getSectionFinancials",
    saveSectionNotification: "saveSectionNotification",
    getSectionNotifications: "getSectionNotifications",
    saveSectionDiscount: "saveSectionDiscount",
    removeSectionDiscounts: "removeSectionDiscounts",
    getSectionDiscounts: "getSectionDiscounts",
    getAvailableDiscountPrograms: "getAvailableDiscountPrograms",
    getAvailableOfferingFinancials: "getAvailableOfferingFinancials",
    getAvailableFacultyWithFinancials: "getAvailableFacultyWithFinancials",
    getAvailableResourcesWithFinancials: "getAvailableResourcesWithFinancials",
    getAvailableMarketingProgramsWithFinancials: "getAvailableMarketingProgramsWithFinancials",
    removeFinancials: "removeFinancials",
    removeMeetings: "removeMeetings",
    removeLocations: "removeLocations",
    removeInstructors: "removeInstructors",
    removeMeetingInformations: "removeMeetingInformations",
    findRoom: "findRoom",
    saveLocations: "saveLocations",
    saveGeneralComment: "saveGeneralComment",
    saveFacultyComment: "saveFacultyComment",
    saveEnrollmentComment: "saveEnrollmentComment",
    findGeneralCommentHistory: "findGeneralCommentHistory",
    findFacultyComments: "findFacultyComments",
    findEnrollmentCommentHistory: "findEnrollmentCommentHistory",
    findFaculty: "findFaculty",
    findEnrollmentStudentHistory: "findEnrollmentStudentHistory",
    scheduleInstructor: "scheduleInstructor",
    saveMeetingInformations: "saveMeetingInformations"
  }
}

export default ApiMethodFactory(config)
